CREATE TABLE loginput (
	log_ts	timestamp not null default now(),
	wood_avail	boolean,
	public_heat	boolean,
	private_heat	boolean,
	hot_water	boolean,
	water_bottom	numeric(10,2),
	water_middle	numeric(10,2),
	light_level	int4,
	solar_pump	boolean,
	boiler_temp	numeric(10,2),
	tank_temp	numeric(10,2),
	boiler_run	boolean,
	boiler_fire	boolean,
	aquistat	boolean,
	kw_now		numeric(10,2),
	kw_today	numeric(10,2),
	kw_peak_today	numeric(10,2));

CREATE TABLE logdata (
	id	serial primary key,
	log_ts	timestamp unique not null,
	wood_avail	boolean,
	public_heat	boolean,
	private_heat	boolean,
	hot_water	boolean,
	water_bottom	numeric(10,2),
	water_middle	numeric(10,2),
	light_level	int4,
	solar_pump	boolean,
	boiler_temp	numeric(10,2),
	tank_temp	numeric(10,2),
	boiler_run	boolean,
	boiler_fire	boolean,
	aquistat	boolean,
	kw_now		numeric(10,2),
	kw_today	numeric(10,2),
	kw_peak_today	numeric(10,2));

